homePage.controller('video', function($scope){
	var videoObj = $scope.videoObj = {
		
	};
	videoObj.pageIndex=window.location.search.split('=')[1];
	videoObj.categoryIndex=1;
	videoObj.categoryClickParameter="";
	/*home假数据*/
	videoObj.category=[
		{name:"入门书籍",img:"img/video/category1.png",on:"videoObj.beginList"},
		{name:"用户研究",img:"img/books/category2.png",on:"videoObj.userList",describe:"用户研究是用户中心的设计流程中的第一步。它是一种理解用户，将他们的目标、需求与您的商业宗旨相匹配的理想方法。用户研究重点工作在于研究用户的痛点。"},
		{name:"交互设计",img:"img/books/category3.png",on:"videoObj.interactionList",describe:"用户体验是支撑交互设计进行的关键,它能够让设计师更好地改进设计中的不足,使产品更加优化,并且它也是用户对产品产生好坏印象的关键。"},
		{name:"视觉设计",img:"img/books/category4.png",on:"videoObj.visualList",describe:"以用户为中心的设计思想为指导，通过分析视觉设计在界面设计，进行视觉设计。"},
	];
	videoObj.list=[
		[
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
		],[
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
			{id:"video1",img:"img/video/videoImg1.jpg",name:'深度访谈的十二招技巧',duration:"3小时7分",update:"7-14"},
		],
		[
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
			{id:"video2",img:"img/video/videoImg2.jpg",name:'先有用户体验再有交互设计',duration:"3小时7分",update:"7-14"},
		],
		[
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
			{id:"video3",img:"img/video/videoImg3.jpg",name:'用户体验与网站设计',duration:"3小时7分",update:"7-14"},
		],
	]
	$scope.information=[
		{title:"阅读排行",content1:"如何自学UX",content2:"UX设计作品展开说",content3:"UI,UE,UX三者区别",content4:"UX就业前景"},
		{title:"我的问题",content1:"UX与UI的区别",content2:"自学UX怎么开始",content3:"如何基于UX进行用户研究",content4:"UI的发展"},
		{title:"我的随笔",content1:"我看了用户体验要用",content2:"UX设计作品展开说",content3:"UI，UX，UE三者的区别",content4:"UX就业前景"},
		{title:"我所关注",content1:"UI的未来",content2:"人人都是产品经理",content3:"ZAKER",content4:"说多了都是泪"}
	];
	$scope.pageNum=4;
	//点击分类
	videoObj.category=function(a){
		if(a=="a"){
			videoObj.categoryImgLeft=98;
			videoObj.categoryOn=videoObj.list[0];
			videoObj.categoryIndex=1;

		};if(a=="b"){
			videoObj.categoryImgLeft=250;
			videoObj.categoryOn=videoObj.list[1];
			videoObj.categoryIndex=2;
		};
		;if(a=="c"){
			videoObj.categoryImgLeft=402;
			videoObj.categoryOn=videoObj.list[2];
			videoObj.categoryIndex=3;
		};;if(a=="d"){
			videoObj.categoryImgLeft=552;
			videoObj.categoryOn=videoObj.list[3];
			videoObj.categoryIndex=4;
		};
		(function(){
					$classificationImg=$(".classificationImg");
					$classificationText=$(".classificationText");
					$classificationText.click(
						function(){
							$classificationImg.css("left",videoObj.categoryImgLeft+"px");
						}
					)
				})();
		};
	videoObj.categoryOn=videoObj.list[0];
	if(videoObj.pageIndex=="video1"){
		videoObj.categoryOn=videoObj.list[0];
		videoObj.categoryIndex=1;
	};if(videoObj.pageIndex=="video2"){
		videoObj.categoryOn=videoObj.list[1];
		videoObj.categoryIndex=2;
	};if(videoObj.pageIndex=="video3"){
		videoObj.categoryOn=videoObj.list[2];
		videoObj.categoryIndex=3;
	};if(videoObj.pageIndex=="video4"){
		videoObj.categoryOn=videoObj.list[3];
		videoObj.categoryIndex=4;
	};
	
	
	
	
	
	
});